### ISSUE TITLE
splash is show，but level is'nt loading

### ISSUE THREAD

**Issue by longlongwaytogo** [uniflare/SplashExample#1]
When the splash display, the thread is blocked, Load level also stop execution, until the spash disappeared after the load level, is not where I use the wrong?

**Comment by uniflare** [comment]
Sorry for the late reply-

Yes it is thread-blocking.
Adjust the time by setting the appropriate CVARS in your cfg file.

Are you looking for a "skip" feature?

thanks

PS: The main thread is blocked for the preset time set in your cfg file.
This is required for the minimal nature of the plugin. If you are hoping to "load level" whilst showing the splash - that is not possible with this plugin. Although it would be fairly minor tweaking to change this behaviour - but would break for example if you use scaleform ui - the scaleform will override the splash, which means the GameSDK would be incompatible.

**Comment by longlongwaytogo** [comment]
Thanks for your reply
I  seting the time at cfg file。But it does not reach the results I want, I need to show the loading progress. I will try other ways, and thank you for your reply.

**Comment by uniflare** [comment]
Not possible as the plugin stands now.
It would require removing the blocking draw loop and replacing it with a hooked PostUpdate() method from an IGameFrameworkListener. Then modifying all the cvars/time length routine etc to reflect the change. Bear in mind scaleform will override any pushed render objects via this method. So that is something you will have to tweak if you use it.

good luck

**Comment by uniflare** [comment]
Closing this as it is unintended functionality and unlikely to be implemented.
